CREATE DATABASE HW3_BP;
GO

USE HW3_BP;
GO

DROP TABLE IF EXISTS ENROLLMENTS;
DROP TABLE IF EXISTS COURSE;
DROP TABLE IF EXISTS STUDENT;

CREATE TABLE STUDENT(studentid int PRIMARY KEY,name varchar(32),age int,department VARCHAR (32));

CREATE TABLE COURSE(courseid int PRIMARY KEY,name varchar(32),credits int);

CREATE TABLE ENROLLMENTS(
	eID int PRIMARY KEY,
	sID int FOREIGN KEY REFERENCES STUDENT(studentid),
	cID int FOREIGN KEY REFERENCES COURSE(courseid),
	grade VARCHAR(1)
);

INSERT INTO STUDENT VALUES (23505, 'Javier', 20, 'Art');
INSERT INTO COURSE VALUES (10001, 'Intro to Art', 3);
INSERT INTO ENROLLMENTS VALUES (1, 23505, 10001, 'A');

SELECT * FROM STUDENT;
GO

SELECT * FROM COURSE;
GO

SELECT * FROM ENROLLMENTS;
GO
